language: python
cache: pip
jobs:
  include:
  - stage: unit test
    name: Python 3.6 on Linux with Code Coverage
    python: 3.6
    env: TOXENV=py36-tests-cov
    after_success: codecov
  - name: Python 3.7 on Linux
    python: 3.7
    env: TOXENV=py37-tests
  - name: Python 3.8 on Linux
    python: 3.8
    env: TOXENV=py38-tests
  - name: Python 3.8 on Linux without libyaml
    python: 3.8
    env: TOXENV=py38-tests-nolibyaml
  - name: Python 3.9 on Linux
    python: 3.9
    env: TOXENV=py39-tests
  - name: Linter
    python: 3.6
    env: TOXENV=lint

  - stage: integration test
    name: Python 3.6 on Windows for End2End tests
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.6
    - python -m pip install --upgrade pip
    env:
      - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      - TOXENV=py36-tests-win
      - includeE2E=True

  - stage: deploy
    name: "Deploy to PyPI"
    install: pip install pystache gitchangelog
    script: gitchangelog > CHANGELOG.md
    deploy:
      provider: pypi
      username: "__token__"
      password:
        secure: YJxAQkupOv8mC5ubhWj7QY0ZkqcUFStmkc7EwD/1cNwF7cRautZnMWurD6+7YqqhsLOPSxTtT0CsvKF0rH9nI+Zx4iL1dIW+u6zypR0Tgjfj/Xl1GgWxcBxlRXHqw8anALcFyD1+MKES6HFbrb06xf8fiTHNb4Dy17BxivxGub/wYqzfmYlnszQWse9bPjCdf+4IaB5YGaGt2wCjBzbGPQ0erlxz7k9+VA+2mUPVoJzpZ5hZMSB5WOapwV4/yPGy8Xt6HQD5Gtlu8afRwvmQEBK7s68MANcjpxv4q9FYqfZd5iGfmi6sFgWQ5g1zsREYfMlwV0MS2pyLwisah9W2AuRzQpVTis6D/Odod2ebnVBQoR5e9NJDeAmrQ7qBGtX5OLi7XPgcxCjGSmvIlxSwt4GYS11C872ITBiJyLFGYstGVM0U5IXWGsbfTYo6pncO7jDckN9VSQILpjxn8BwUP9oTBmo9MXnkBy3l0kyO0Is5W/cpd9aGN+02q2Lh98KYW/6T4/sj1cUEzccHUMmvWiKxeis8eZVJ/P1cC607fvitmqKpLDctFX+37G66m+jpReaXAfa59fFWkjWRzRD+lxcvlsoczizyP/CgOnKTtHyvhRlURYY8USFDouZRcdQ5mm4BqrCJ80CyHJpSqBv0cIOkWwLi2QeynviH4rey86U=
      on:
        tags: true
      skip_existing: true
      distributions: "sdist bdist_wheel"

install:
  - pip install tox
  - if [ "$TOXENV" = "py36-tests-cov" ]; then pip install codecov; fi

script: tox
